module.exports = {
  hualien: {
    label:'花蓮', center:[23.85,121.45], zoom:10,
    markers:[
      { name:'亞東預拌混凝土（美崙廠）', addr:'花蓮市美工三街12號', lat:24.0164108, lng:121.6320073, group:'5star',
        detail:'母公司亞泥100%轉投資，資本額20億｜設廠2001年｜全台13廠｜產能180m³/h',
        specs:'設備 3m³×1｜設計產能 140m³/hr｜年銷 63,931m³｜人力合計 11人', relations:null },
      { name:'台灣水泥花蓮廠（預拌混凝土工場）', addr:'花蓮市民孝里精美路2-1號', lat:24.0138314, lng:121.6289907, group:'5star',
        detail:'台泥集團｜預拌工場1994年｜花蓮另有水泥廠+和平UHPC中心', specs:'設備 3m³×1｜設計產能 140m³/hr｜年銷由鳳勝代工｜人力合計 10人', relations:null },
      { name:'鳳勝實業（花蓮廠）', addr:'花蓮市美工五街3號', lat:24.0134506, lng:121.6340555, group:'4star',
        detail:'母公司資本額6億｜台泥+官田鋼鐵股東｜全台11預拌廠+2砂石廠',
        specs:'設備 3m³×1｜設計產能 130m³/hr｜年銷含代工 114,728m³｜人力合計 12人', relations:null },
      { name:'鼎泰興預拌混凝土', addr:'新城鄉新城村新興一路1巷6號', lat:24.1294355, lng:121.6428992, group:'3star',
        detail:'資本額4,100萬｜2003年設立(原名龍華預拌)｜負責人黃銘華', relations:null },
      { name:'威神企業', addr:'吉安鄉光華村華城六街35號', lat:23.9249937, lng:121.5825473, group:'3star',
        detail:'資本額4,800萬｜1987年｜負責人梁億宏｜預拌+土石採取+廢棄物清除',
        relations:{me:'威神企業', members:[{name:'梁億宏',role:'董事長',companies:['威神企業','億鍠營造']},{name:'陳月嬌',role:'董事',companies:['威神企業']},{name:'陳玉官',role:'董事',companies:['威神企業']}]}},
      { name:'友誠有限公司', addr:'秀林鄉和平村和平30-11號', lat:24.2940384, lng:121.6023807, group:'3star',
        detail:'資本額3,000萬｜1994年｜負責人方來興｜預拌+瀝青｜和平工業區',
        relations:{me:'友誠', members:[{name:'方來興',role:'負責人',companies:['友誠','友正預拌混凝廠','友砂預拌廠','友正貨運','友華加油站']}]}},
      { name:'友正預拌混凝廠', addr:'吉安鄉光華村華工六路31巷2號', lat:23.9354502, lng:121.5903549, group:'2star',
        detail:'資本額2,000萬｜1992年｜含崇德廠(秀林)+光復廠｜友正集團核心',
        specs:'設備 3m³×2｜設計產能 270m³/hr｜年銷 100,000m³｜人力合計 17人',
        relations:{me:'友正預拌混凝廠', members:[
          {name:'馮志緯',role:'董事長',companies:['友正預拌混凝廠','友正貨運(監察人)']},
          {name:'方來興',role:'董事',companies:['友正預拌混凝廠','友誠','友砂預拌廠','友正貨運','友華加油站']},
          {name:'方彥翔',role:'董事',companies:['友正預拌混凝廠','友砂預拌廠','友正砂石','方嘉建設']},
          {name:'林化應',role:'董事',companies:['友正預拌混凝廠','友正貨運']},
          {name:'陳東堯',role:'監察人',companies:['友正預拌混凝廠','花建實業','友正貨運']}]}},
      { name:'花建實業', addr:'鳳林鎮榮開路39-1號', lat:23.7698653, lng:121.4910701, group:'2star',
        detail:'資本額1,800萬｜1990年｜負責人陳東堯(前方來興)｜友正集團關聯',
        relations:{me:'花建實業', members:[
          {name:'陳東堯',role:'負責人',companies:['花建實業','友正預拌混凝廠(監察人)','友正貨運']},
          {name:'方來興',role:'前負責人',companies:['花建實業(前)','友誠','友正預拌混凝廠','友砂預拌廠','友正貨運','友華加油站']}]}},
      { name:'長雄預拌混凝土廠', addr:'吉安鄉仁安村南海四街148號', lat:23.9520915, lng:121.5931644, group:'2star',
        detail:'資本額500萬｜1973年(50年老廠)｜邱氏家族(持股86%)｜年銷100,000m³｜人均效率最高',
        specs:'設備 3m³×1｜設計產能 140m³/hr｜年銷 100,000m³｜人力合計 13人',
        relations:{me:'長雄預拌混凝土廠', members:[
          {name:'邱豐娥',role:'董事長',companies:['長雄預拌混凝土廠','長旭建設']},
          {name:'邱雪萍',role:'董事',companies:['長雄預拌混凝土廠']},
          {name:'邱如茵',role:'董事',companies:['長雄預拌混凝土廠']},
          {name:'邱錫樑',role:'監察人',companies:['長雄預拌混凝土廠','長旭交通']}]}},
      { name:'友砂預拌廠', addr:'花蓮市國裕里富裕十街50巷17號', lat:23.9968395, lng:121.5977027, group:'2star',
        detail:'資本額2,000萬｜1998年｜友正集團關係企業',
        relations:{me:'友砂預拌廠', members:[
          {name:'方冠儒',role:'負責人',companies:['友砂預拌廠']},
          {name:'方來興',role:'董事',companies:['友砂預拌廠','友正預拌混凝廠','友誠','友正貨運','友華加油站']},
          {name:'方彥翔',role:'董事',companies:['友砂預拌廠','友正預拌混凝廠','友正砂石','方嘉建設']}]}},
      { name:'大元預拌混凝土', addr:'吉安鄉仁安村南海七街47號', lat:23.9452078, lng:121.5928811, group:'1star',
        detail:'資本額500萬｜2022年新設｜負責人温茗勝｜工廠：玉里鎮新民8-1號',
        relations:{me:'大元預拌混凝土', members:[{name:'温茗勝',role:'負責人',companies:['大元預拌混凝土','大元行','芊成工程']}]}},
      { name:'定穎預拌混凝土（吉安廠）', addr:'吉安鄉', lat:23.9700, lng:121.5960, group:'2star',
        detail:'設備 2m³×1｜產能 80m³/hr｜年銷 30,000m³｜9 人精簡編制',
        specs:'設備 2m³×1｜產能 80m³/hr｜年銷 30,000m³｜人力合計 9人', relations:null },
      { name:'政旺企業（股）', addr:'光復鄉中華路256巷17號', lat:23.6707166, lng:121.4242939, group:'2star',
        detail:'資本額500萬｜1980年｜2025/10負責人變更為張榮耀', relations:null },
      { name:'貫天下預拌混凝土（股）', addr:'瑞穗鄉瑞北村30號', lat:23.5324636, lng:121.3763246, group:'2star',
        detail:'資本額50萬(原800萬2022改組)｜負責人王祥富｜月均5,000–6,000m³', relations:null },
      { name:'陸紀實業有限公司', addr:'瑞穗鄉鶴岡村興鶴路二段368號', lat:23.5593331, lng:121.3958327, group:'2star',
        detail:'資本額1,000萬｜1995年｜負責人李煥陞', relations:null },
      { name:'錦山企業有限公司', addr:'富里鄉石牌村車站街一段35之2號', lat:23.1827030, lng:121.2516392, group:'2star',
        detail:'資本額500萬｜1998年｜負責人邱洪章｜前身全章企業社', relations:null },
      { name:'展信實業有限公司', addr:'玉里鎮大禹里大禹202-4號', lat:23.3795730, lng:121.3253466, group:'3star',
        detail:'資本額2,950萬｜1992年｜負責人曾雲嬌｜月均4,000m³｜關係：展信營造', relations:null },
      { name:'利泰工程行', addr:'光復鄉大馬村中華路382號1樓', lat:23.6640, lng:121.4250, group:'1star',
        detail:'資本額48萬｜1991年｜合夥組織(鄭火榮)', relations:null },
      { name:'鳳勝實業（壽豐廠）', addr:'花蓮縣壽豐鄉月眉路3段72號', lat:23.87, lng:121.509, group:'4star' },
    ]
  },
  yilan: {
    label:'宜蘭', center:[24.68,121.77], zoom:11,
    markers:[
      { name:'台泥宜蘭分廠', addr:'員山鄉蓁巷村員山路二段438號', lat:24.7241679, lng:121.7104327, group:'5star',
        detail:'台泥集團GRMC#109｜1套拌和設備+19車｜廠長：洪崇智', relations:null },
      { name:'潤泰精密材料冬山廠', addr:'冬山鄉安平村大安路357號', lat:24.6223238, lng:121.7802177, group:'5star',
        detail:'潤泰集團｜原力霸水泥冬山廠｜水泥研磨+乾粉砂漿+預拌混凝土', relations:null },
      { name:'宜興預拌混凝土（總部）', addr:'冬山鄉龍德工業區德興六路43號', lat:24.6310386, lng:121.8224140, group:'4star',
        detail:'宜蘭最大GRMC#040｜資本額1.72億｜1996年｜負責人:李興和',
        relations:{me:'宜興預拌混凝土', members:[
          {name:'李興和',role:'董事長',companies:['宜興預拌混凝土','武雄實業(董事長)','梅洲混凝土(董事)','藍園營造','蘇澳石礦']},
          {name:'林贊壽',role:'董事',companies:['宜興預拌混凝土','梅洲混凝土(董事長)','靖瑋營造','蘇澳石礦(負責人)','武雄實業(監察人)','億茂汽車貨運']},
          {name:'李伯恩',role:'董事',companies:['宜興預拌混凝土']},
          {name:'陳明月',role:'董事',companies:['宜興預拌混凝土','武雄實業(董事)','梅洲混凝土(董事)']},
          {name:'李松輝',role:'董事',companies:['宜興預拌混凝土']},
          {name:'謝心悅',role:'董事',companies:['宜興預拌混凝土']},
          {name:'陳正添',role:'監察人',companies:['宜興預拌混凝土','梅洲混凝土(監察人)']}]}},
      { name:'宜興預拌混凝土（冬山二廠）', addr:'冬山鄉德興五路36號', lat:24.6575, lng:121.7880, group:'4star',
        detail:'宜興集團二廠｜3套拌和設備｜2003年', relations:null },
      { name:'宜興預拌混凝土（冬山三廠）', addr:'冬山鄉德興六路41~43號', lat:24.6565, lng:121.7898, group:'4star',
        detail:'宜興集團三廠｜2012年', relations:null },
      { name:'宜興預拌混凝土（宜蘭梅洲廠）', addr:'宜蘭市梅洲二路127號', lat:24.7540, lng:121.7400, group:'4star',
        detail:'宜興集團梅洲廠｜2013年｜宜蘭市北側梅洲工業區', relations:null },
      { name:'久屋預拌混凝土', addr:'冬山鄉龍祥十路19號', lat:24.6278383, lng:121.8129374, group:'3star',
        detail:'資本額8,000萬｜1982年｜負責人:簡志耀｜員工26人',
        relations:{me:'久屋預拌混凝土', members:[
          {name:'簡志耀',role:'董事長',companies:['久屋預拌混凝土','金滿億珠寶銀樓','金寶玉銀樓']},
          {name:'李茂榮',role:'董事',companies:['久屋預拌混凝土']},
          {name:'游正雄',role:'董事',companies:['久屋預拌混凝土']},
          {name:'蔡宏裕',role:'監察人',companies:['久屋預拌混凝土']},
          {name:'張琇喬',role:'監察人',companies:['久屋預拌混凝土']}]}},
      { name:'立泰預拌混凝土工業', addr:'冬山鄉龍祥十路5號', lat:24.6278383, lng:121.8129374, group:'3star',
        detail:'資本額5,000萬｜1993年｜負責人:楊欣浩｜員工34人｜兼營瀝青混凝土',
        relations:{me:'立泰預拌混凝土', members:[
          {name:'楊欣浩',role:'董事長',companies:['立泰預拌混凝土']},
          {name:'廖淑芬',role:'董事',companies:['立泰預拌混凝土']},
          {name:'楊純玲',role:'董事',companies:['立泰預拌混凝土']},
          {name:'林建章',role:'監察人',companies:['立泰預拌混凝土']}]}},
      { name:'享正實業', addr:'冬山鄉德興一路42號', lat:24.6247967, lng:121.8211877, group:'3star',
        detail:'資本額4,968萬｜1987年｜負責人:林文政｜ISO9002｜2套拌合機+15車',
        relations:{me:'享正實業', members:[
          {name:'林文政',role:'董事長',companies:['享正實業']},
          {name:'洪裕健',role:'董事',companies:['享正實業']},
          {name:'林秀春',role:'監察人',companies:['享正實業']}]}},
      { name:'得福混凝土工業', addr:'冬山鄉成興路42號', lat:24.6360639, lng:121.7948693, group:'3star',
        detail:'資本額6,000萬｜1979年｜董事長:連志峯｜與福得關聯',
        relations:{me:'得福混凝土', members:[
          {name:'連志峯',role:'董事長',companies:['得福混凝土','福得混凝土(董事)','銀燦有限公司']},
          {name:'吳智翔',role:'董事',companies:['得福混凝土','福得混凝土(董事長)','吉祥機車行']},
          {name:'連怡雲',role:'董事',companies:['得福混凝土']},
          {name:'薛豐文',role:'監察人',companies:['得福混凝土','福得混凝土(董事)']}]}},
      { name:'福得混凝土工業', addr:'宜蘭市梅洲二路97號', lat:24.7805177, lng:121.7354767, group:'2star',
        detail:'資本額4,160萬｜1985年｜董事長:吳智翔｜連志峯為董事',
        relations:{me:'福得混凝土', members:[
          {name:'吳智翔',role:'董事長',companies:['福得混凝土','得福混凝土(董事)','吉祥機車行']},
          {name:'薛豐文',role:'董事',companies:['福得混凝土','得福混凝土(監察人)']},
          {name:'連志峯',role:'董事',companies:['福得混凝土','得福混凝土(董事長)','銀燦有限公司']},
          {name:'連志豪',role:'監察人',companies:['福得混凝土']}]}},
      { name:'禹盛混凝土有限公司', addr:'宜蘭縣三星鄉月眉村星中路157號', lat:24.666, lng:121.6532, group:'2star',
        detail:'資本額待查｜三星鄉預拌廠 | TRMC會員', relations:null },
      { name:'梅洲混凝土工業股份有限公司', addr:'宜蘭縣宜蘭市梅洲二路57號', lat:24.752, lng:121.7533, group:'2star',
        detail:'資本額待查｜宜蘭市梅洲工業區｜宜興集團林贊壽擔任董事長', relations:null },
    ]
  },
    taipei: {
    label:'北區（台北·新北·基隆）', center:[25.07,121.56], zoom:10,
    markers:[
      { name:'國產建材實業（台北港廠）', addr:'八里區商港路128號', lat:25.1499958, lng:121.3930364, group:'5star',
        detail:'國產建材2504｜全台最大預拌集團｜智慧廠', relations:null },
      { name:'國產建材實業（汐止廠）', addr:'汐止區福德二路360號', lat:25.0661912, lng:121.6338472, group:'5star',
        detail:'國產建材｜汐止二廠2024動工｜年產30萬m³', relations:null },
      { name:'國產建材實業（土城廠）', addr:'土城區中華路二段202號', lat:24.9695713, lng:121.4372831, group:'5star',
        detail:'國產建材｜土城廠｜廠長陳丁郎', relations:null },
      { name:'國產建材實業（八里廠）', addr:'八里區龍米路二段221號', lat:25.1585809, lng:121.4304577, group:'5star',
        detail:'國產建材｜八里廠', relations:null },
{ name:'國產建材實業（基隆廠）', addr:'基隆市七堵區八德路2-2號', lat:25.103064, lng:121.7224644, group:'5star',
        detail:'國產建材｜基隆廠｜七堵區八德里', relations:null },
      { name:'亞東預拌混凝土（汐止廠）', addr:'汐止區大同路一段138號', lat:25.0558581, lng:121.6314672, group:'5star',
        detail:'遠東集團/亞泥100%持股｜資本額20億｜全台26廠｜負責人李坤炎', relations:null },
      { name:'亞東預拌混凝土（土城廠）', addr:'土城區中華路二段208號', lat:24.9691936, lng:121.4373806, group:'5star',
        detail:'遠東集團/亞泥｜廠長朱文壽', relations:null },
      { name:'台灣水泥台北水泥製品廠', addr:'汐止區大同路一段310號', lat:25.0580012, lng:121.6371891, group:'5star',
        detail:'台泥集團1101｜資本額1,000億｜廠長陳竹村｜1套拌和設備', relations:null },
      { name:'力泰建設企業（士林廠）', addr:'士林區延平北路七段7號', lat:25.1007798, lng:121.4902192, group:'4star',
        detail:'上柜5520｜資本額7.38億｜負責人吳良材｜北部最大獨立業者', relations:null },
      { name:'力泰建設企業（汐止廠）', addr:'汐止區樟樹二路43號', lat:25.0621481, lng:121.6396738, group:'4star',
        detail:'力泰建設汐止廠',
        relations:{me:'力泰建設企業', members:[
          {name:'吳良材', role:'董事長兼總經理', companies:['力泰建設企業']},
          {name:'吳劉冠伶', role:'董事', companies:['力泰建設企業','富源投資']},
          {name:'李義雄', role:'董事', companies:['力泰建設企業','上甘利投資']},
          {name:'朱風鳴', role:'獨立董事', companies:['力泰建設企業']},
          {name:'高富銓', role:'獨立董事', companies:['力泰建設企業']}
        ]} },
      { name:'幸孚預拌混凝土（土城廠）', addr:'土城區中華路一段162號', lat:24.9835398, lng:121.4415041, group:'4star',
        detail:'幸福水泥關係｜資本額8.8億｜負責人陳韻如｜樹林+五股+汐止+基隆共5廠', relations:null },
      { name:'幸孚預拌混凝土（基隆廠）', addr:'基隆市七堵區八德路2-10號', lat:25.1128261, lng:121.7276096, group:'4star',
        detail:'幸福水泥關係｜基隆七堵', relations:null },
      { name:'信一預拌混凝土', addr:'中正區寶慶路37號8樓', lat:25.041485, lng:121.5103107, group:'3star',
        detail:'資本額1.1億｜1990年｜負責人楊智雄｜信大水泥關係', relations:null },
      { name:'合興預拌混凝土（三峯廠）', addr:'三峯區中正路三段196號', lat:24.9040392, lng:121.3503511, group:'3star',
        detail:'資本額4,500萬｜1992年｜負責人鄧桂英｜GRMC認證', relations:null },
      { name:'大象實業', addr:'汐止區環河街126號', lat:25.0593311, lng:121.6293336, group:'3star',
        detail:'資本額4,189萬｜1995年｜負責人謝英美｜GRMC認證', relations:null },
      { name:'和昌國際工業（汐止廠）', addr:'汐止區保新街133-1號', lat:25.0723776, lng:121.6859409, group:'4star',
        detail:'原台產實業｜和昌國際工業購入｜資本額4.85億｜負責人江程金',
        relations:{me:'和昌國際工業', members:[
          {name:'江程金', role:'董事長', companies:['和昌國際工業','皇昌營造','環東投資','富謙投資']},
          {name:'江家明', role:'董事', companies:['和昌國際工業']},
          {name:'姚漢卿', role:'監察人', companies:['和昌國際工業']}
        ]} },
      { name:'和昌國際工業（內湖廠）', addr:'內湖區安康路111號', lat:25.062775, lng:121.598431, group:'4star',
        detail:'和昌國際工業｜資本額4.85億｜負責人江程金｜GRMC認證｜汐止廠+觀音廠+楊梅廠',
        relations:{me:'和昌國際工業', members:[
          {name:'江程金', role:'董事長', companies:['和昌國際工業','皇昌營造','環東投資','富謙投資']},
          {name:'蔡萬興', role:'監察人', companies:['和昌國際工業']},
          {name:'鄭詩品', role:'監察人', companies:['和昌國際工業']},
          {name:'劉秋霞', role:'董事', companies:['和昌國際工業']},
          {name:'李彥德', role:'董事', companies:['和昌國際工業']}
        ]} },
      { name:'陽明混凝土', addr:'金山區南勢湖41號', lat:25.216642, lng:121.615173, group:'3star',
        detail:'資本額2,000萬｜1994年｜負責人郭淑如｜北海岸', relations:null },
      { name:'大漢預拌廠', addr:'泰山區中港南路310號1樓', lat:25.0566066, lng:121.4380565, group:'2star',
        detail:'資本額2,000萬｜1987年｜負責人蔡錦達', relations:null },
      { name:'宥辰興業', addr:'鶯歌區中正三路156巷26號2樓', lat:24.9411175, lng:121.3384942, group:'3star',
        detail:'資本額4億｜2016年｜負責人藍隆寬｜預拌混凝土製造',
        relations:{me:'宥辰興業', members:[
          {name:'藍隆寬', role:'董事長', companies:['宥辰興業','宥合實業']},
          {name:'賴聰銘', role:'監察人', companies:['宥辰興業']}
        ]} },
      { name:'聯興建材工業', addr:'新店區安和路二段146巷30號', lat:24.9719822, lng:121.5194806, group:'2star',
        detail:'獨立｜新店', relations:null },
{ name:'富品混凝土工業', addr:'貢寮區延平街177號', lat:25.0569387, lng:121.9246477, group:'2star',
        detail:'獨立｜東北角', relations:null },
      { name:'松達建材', addr:'汐止區南陽街120巷35號1樓', lat:25.0598359, lng:121.6230571, group:'2star',
        detail:'資本額7,000萬｜白珮妤｜1988年｜預拌混凝土製造',
        relations:{me:'松達建材', members:[
          {name:'白珮妤', role:'董事長', companies:['松達建材','世永']},
          {name:'白添順', role:'監察人', companies:['松達建材']},
          {name:'黃建榮', role:'董事', companies:['松達建材']},
          {name:'黃淑玲', role:'董事', companies:['松達建材']},
          {name:'郭宏正', role:'董事', companies:['松達建材']}
        ]} },
      { name:'龍形企業（八里廠）', addr:'新北市八里區忠八街60號', lat:25.1620004, lng:121.4196045, group:'3star',
        detail:'資本額8,000萬｜1991年｜負責人施阿祥｜ISO-9001｜捷運局合格供應商｜實績：台北港、十三行博物館',
        relations:{me:'龍形企業', members:[
          {name:'施阿祥', role:'董事長', companies:['龍形企業','龍翔國際船務']},
          {name:'施阿貴', role:'董事', companies:['龍形企業']},
          {name:'呂清棋', role:'董事', companies:['龍形企業']},
          {name:'汪仲凱', role:'董事/總經理', companies:['龍形企業']},
          {name:'吳孟軒', role:'董事', companies:['龍形企業']},
          {name:'林周煙', role:'監察人', companies:['龍形企業']},
          {name:'蔡錦賢', role:'監察人', companies:['龍形企業']}
        ]} },
      { name:'世芳預拌混凝土有限公司', addr:'新北市樹林區中正路205號', lat:24.9907, lng:121.4205, group:'2star',
        detail:'資本額待查｜樹林區預拌廠 | TRMC會員', relations:null },
    ]
  },
  taoyuan: {
    label:'桃園', center:[24.99,121.30], zoom:10,
    markers:[
      { name:'國產建材實業（林口廠）', addr:'桃園市龜山區樂善里文明路17號', lat:25.0624657, lng:121.3768616, group:'5star',
        detail:'國產建材2504｜全台最大預拌集團｜桃園龜山', relations:null },
      { name:'國產建材實業（蘆竹二廠）', addr:'桃園市蘆竹區內厝里長興路三段277巷10號', lat:25.0860, lng:121.2930, group:'5star',
        detail:'國產建材｜蘆竹二廠｜1998年設立｜供應青埔/航空城', relations:null },
      { name:'亞東預拌混凝土（桃園廠）', addr:'桃園市蘆竹區興隆街42號', lat:25.0420, lng:121.2980, group:'5star',
        detail:'遠東集團/亞泥100%｜資本額20億｜桃園區營運總廠｜轄新屋八德分廠', relations:null },
      { name:'亞東預拌混凝土（八德廠）', addr:'桃園市八德區興豐路2350巷369號', lat:24.9422293, lng:121.312636, group:'5star',
        detail:'遠東集團/亞泥｜設備 3m³×2｜產能 360m³/hr｜桃園三廠122車', relations:null },
      { name:'亞東預拌混凝土（新屋廠）', addr:'桃園市新屋區鼎鐘路210號', lat:24.9690, lng:121.0480, group:'5star',
        detail:'遠東集團/亞泥｜設備 3m³×1｜產能 170m³/hr', relations:null },
      { name:'亞東預拌混凝土（林口廠）', addr:'桃園市龜山區大崗里頂湖28號', lat:25.045329, lng:121.356307, group:'5star',
        detail:'遠東集團/亞泥｜GRMC認證', relations:null },
      { name:'台灣水泥（龜山分廠）', addr:'桃園市龜山區龍壽里東萬壽路688號', lat:25.0143535, lng:121.3925936, group:'5star',
        detail:'台泥集團1101｜龜山分廠', relations:null },
      { name:'台灣水泥（桃園二廠）', addr:'桃園市蘆竹區六福路59號', lat:25.0615695, lng:121.2955674, group:'5star',
        detail:'台泥集團｜桃園二廠', relations:null },
      { name:'台灣水泥（桃園分廠）', addr:'桃園市蘆竹區南山路二段220號', lat:25.0556663, lng:121.2902556, group:'5star',
        detail:'台泥集團｜桃園分廠', relations:null },
      { name:'新三亞預拌混凝土廠', addr:'桃園市龍潭區龍源路81號', lat:24.8639321, lng:121.2099045, group:'4star',
        detail:'資本額6,000萬｜1999年｜負責人陳易穰｜GRMC綠混凝土認證｜金石獎｜公共工程9成',
        specs:'設備 3m³×2｜桃園廠+龍潭廠｜公共工程/廠辦/住宅', relations:null },
      { name:'慶龍預拌混凝土', addr:'桃園市蘆竹區內溪路自強巷2號', lat:25.0390, lng:121.2910, group:'3star',
        detail:'資本額1億｜1993年｜負責人楊進連｜GRMC認證｜另設八德廠',
        relations:{me:'慶龍預拌混凝土', members:[
          {name:'楊進連',role:'董事長',companies:['慶龍預拌混凝土']},
          {name:'陳竹男',role:'董事',companies:['慶龍預拌混凝土']},
          {name:'廖正文',role:'董事',companies:['慶龍預拌混凝土']},
          {name:'陳承勇',role:'董事',companies:['慶龍預拌混凝土']},
          {name:'陳承瑜',role:'董事',companies:['慶龍預拌混凝土']},
          {name:'胡新添',role:'監察人',companies:['慶龍預拌混凝土']}]} },
      { name:'國普混凝土工業', addr:'桃園市蘆竹區興隆街42號', lat:25.0420, lng:121.2980, group:'3star',
        detail:'資本額7,800萬｜1987年｜負責人呂湘香｜預拌混凝土/瀝青/骨材', relations:null },
      { name:'國順預拌混凝土（龍華廠）', addr:'桃園市龜山區龍壽里龍校街32巷40號', lat:25.0030, lng:121.3530, group:'3star',
        detail:'母公司國順預拌資本額2億｜1993年｜負責人劉世翔｜GRMC認證',
        relations:{me:'國順預拌混凝土', members:[
          {name:'劉世翔',role:'董事長',companies:['國順預拌混凝土','昌久金屬科技','鑫沐國際']},
          {name:'王新仁',role:'監察人',companies:['國順預拌混凝土']},
          {name:'游月雲',role:'董事',companies:['國順預拌混凝土']},
          {name:'劉世為',role:'董事',companies:['國順預拌混凝土']},
          {name:'何正偉',role:'董事',companies:['國順預拌混凝土']},
          {name:'林鳳盈',role:'董事',companies:['國順預拌混凝土']}]} },
      { name:'大園預拌混凝土', addr:'桃園市大園區圳頭里後館一路427號', lat:25.0735874, lng:121.2005532, group:'3star',
        detail:'資本額3,600萬｜2003年｜負責人蘇添全', relations:null },
      { name:'慶隆預拌混凝土', addr:'桃園市中壢區普忠路331號', lat:24.9622563, lng:121.2446157, group:'3star',
        detail:'資本額2,988萬｜1996年｜負責人朱瑞爐', relations:null },
      { name:'武雄實業（觀音廠）', addr:'桃園市觀音區草漯里忠孝路645號', lat:25.0290, lng:121.0890, group:'3star',
        detail:'宜興集團李興和關係｜觀音廠｜GRMC認證', relations:null },
      { name:'慶皇水泥', addr:'桃園市觀音區廣興里保興路一段228號', lat:25.0200, lng:121.1060, group:'3star',
        detail:'資本額1.2億｜1995年｜預拌混凝土/水泥製品', relations:null },
      { name:'國產建材實業（中壢廠）', addr:'桃園市平鎮區中豐路南勢一段1號', lat:24.946, lng:121.214, group:'5star' },
      { name:'和昌國際工業（楊梅廠）', addr:'桃園市楊梅區梅獅路一段157號', lat:24.908, lng:121.146, group:'4star' },
      { name:'和昌國際工業（觀音廠）', addr:'桃園市觀音區快速路9段2276巷11號', lat:25.033, lng:121.077, group:'4star' },
      { name:'宜興預拌混凝土（楊梅廠）', addr:'桃園市楊梅區永平里梅獅路一段270號', lat:24.908, lng:121.146, group:'4star' },
      { name:'幸孚預拌混凝土（埔心廠）', addr:'桃園市楊梅區梅獅路1段191號', lat:24.908, lng:121.146, group:'4star' },
    ]
  },
  hsinchu: {
    label:'新竹·苗栗', center:[24.76,120.96], zoom:10,
    markers:[
      { name:'國產建材實業（新竹廠）', addr:'新竹市香山區中華路六段646號', lat:24.731176, lng:120.914507, group:'5star',
        detail:'國產建材2504｜全台最大預拌集團｜28座混凝土廠', relations:null },
      { name:'國產建材實業（東大廠）', addr:'新竹市東大路三段110巷30-1號', lat:24.814, lng:120.935, group:'5star',
        detail:'國產建材｜新竹東大廠', relations:null },
      { name:'國產建材實業（竹北廠）', addr:'新竹縣竹北市東興路二段588巷90號', lat:24.836, lng:121.028, group:'5star',
        detail:'國產建材｜竹北廠', relations:null },
      { name:'國產建材實業（苗栗廠）', addr:'苗栗縣銅鑼鄉中平村忠興街2號', lat:24.483, lng:120.788, group:'5star',
        detail:'國產建材｜苗栗廠', relations:null },
      { name:'亞興水泥製品（新竹廠/亞東關係）', addr:'新竹市東大路三段274號', lat:24.814, lng:120.938, group:'5star',
        detail:'遠東集團亞泥100%轉投資｜資本額1億｜負責人金崇仁｜GRMC認證',
        specs:'竹苗營運處｜竹北廠：竹北市泰和路184號｜電話03-5368405', relations:null },
      { name:'亞興水泥製品（竹北廠/亞東關係）', addr:'新竹縣竹北市泰和路184號', lat:24.8411766, lng:121.0050914, group:'5star',
        detail:'遠東集團亞泥｜亞東預拌竹苗區｜負責人鍾政宗｜1988年設立', relations:null },
      { name:'台灣水泥（新竹分廠）', addr:'新竹縣竹北市博愛街792號', lat:24.844, lng:121.019, group:'5star',
        detail:'台泥集團1101｜新竹分廠｜GRMC認證#107｜360m³/hr｜32車', relations:null },
      { name:'永炬企業', addr:'新竹縣竹東鎮仁愛里北岸6號', lat:24.736, lng:121.081, group:'4star',
        detail:'資本額2億(實收1.25億)｜1981年｜負責人羅煥綺｜羅家家族｜GRMC認證｜ISO9001',
        specs:'設備 400m³/hr｜另設楊梅廠｜砂石/預拌/瀝青｜竹東龍頭', relations:{me:'永炬企業', members:[
          {name:'羅煥綺',role:'董事長',companies:['永炬企業','長順加油站','永炬建設']},
          {name:'羅居榮',role:'董事/總經理',companies:['永炬企業']},
          {name:'羅明坤',role:'董事',companies:['永炬企業']},
          {name:'羅居波',role:'監察人',companies:['永炬企業']}]} },
      { name:'環球混凝土（新竹廠/環泥子公司）', addr:'新竹縣竹東鎮員山路435巷18號', lat:24.783822, lng:121.0438108, group:'4star',
        detail:'環球水泥(環泥)子公司｜資本額1.32億｜預拌/砂石/水泥製品', relations:null },
      { name:'國順預拌混凝土（新竹廠）', addr:'新竹市東區中華路一段1巷26-1號', lat:24.798, lng:120.976, group:'3star',
        detail:'母公司資本額3億(實收2億)｜1993年｜負責人劉世翔｜GRMC認證｜ISO9001',
        specs:'180m³/hr｜4廠(新竹/竹南/苗栗/龍華)｜供應捷運萬大線/桃園綠線', relations:{me:'國順預拌混凝土', members:[
          {name:'劉世翔',role:'董事長',companies:['國順預拌混凝土','昌久金屬科技','鑫沐國際']},
          {name:'王新仁',role:'監察人',companies:['國順預拌混凝土']},
          {name:'游月雲',role:'董事',companies:['國順預拌混凝土']},
          {name:'劉世為',role:'董事',companies:['國順預拌混凝土']},
          {name:'何正偉',role:'董事',companies:['國順預拌混凝土']},
          {name:'林鳳盈',role:'董事',companies:['國順預拌混凝土']}]} },
      { name:'國順預拌混凝土（竹南廠）', addr:'苗栗縣竹南鎮仁愛路1633號', lat:24.690, lng:120.877, group:'3star',
        detail:'國順預拌關係企業｜GRMC認證', relations:{me:'國順預拌混凝土', members:[
          {name:'劉世翔',role:'董事長',companies:['國順預拌混凝土','昌久金屬科技','鑫沐國際']},
          {name:'王新仁',role:'監察人',companies:['國順預拌混凝土']},
          {name:'游月雲',role:'董事',companies:['國順預拌混凝土']},
          {name:'劉世為',role:'董事',companies:['國順預拌混凝土']},
          {name:'何正偉',role:'董事',companies:['國順預拌混凝土']},
          {name:'林鳳盈',role:'董事',companies:['國順預拌混凝土']}]} },
      { name:'國順預拌混凝土（苗栗廠）', addr:'苗栗縣銅鑼鄉中平村中興路18-1號', lat:24.494, lng:120.795, group:'3star',
        detail:'國順預拌關係企業｜GRMC認證', relations:{me:'國順預拌混凝土', members:[
          {name:'劉世翔',role:'董事長',companies:['國順預拌混凝土','昌久金屬科技','鑫沐國際']},
          {name:'王新仁',role:'監察人',companies:['國順預拌混凝土']},
          {name:'游月雲',role:'董事',companies:['國順預拌混凝土']},
          {name:'劉世為',role:'董事',companies:['國順預拌混凝土']},
          {name:'何正偉',role:'董事',companies:['國順預拌混凝土']},
          {name:'林鳳盈',role:'董事',companies:['國順預拌混凝土']}]} },
      { name:'永協企業', addr:'新竹縣湖口鄉成功路910號', lat:24.902, lng:121.047, group:'3star',
        detail:'資本額1億(實收4,500萬)｜1993年｜負責人謝焸麒｜GRMC認證#136｜湖口在地廠', relations:{me:'永協企業', members:[{name:'謝焸麒',role:'董事長',companies:['永協企業','友立科技']},{name:'羅立澂',role:'董事',companies:['永協企業']},{name:'謝素玉',role:'董事',companies:['永協企業']},{name:'羅明志',role:'監察人',companies:['永協企業','羅明志建築師事務所']}]} },
      { name:'毅和實業（寶山廠）', addr:'新竹縣寶山鄉雙溪村三峰路二段385號', lat:24.760, lng:121.022, group:'3star',
        detail:'資本額8,020萬｜1993年｜負責人黃伶｜3廠(寶山/港墘/大厝)｜碳足跡認證',
        specs:'供應台積電竹科/竹南廠｜麗明營造/達欣工程合作', relations:{me:'毅和實業', members:[{name:'黃珉伶',role:'董事長',companies:['毅和實業']},{name:'林慶波',role:'監察人',companies:['毅和實業']}]} },
      { name:'毅和實業（竹南港墘廠）', addr:'苗栗縣竹南鎮港仔墘29-12號', lat:24.687, lng:120.880, group:'3star',
        detail:'毅和實業｜竹南港墘廠', relations:{me:'毅和實業', members:[{name:'黃珉伶',role:'董事長',companies:['毅和實業']},{name:'林慶波',role:'監察人',companies:['毅和實業']}]} },
      { name:'錦鋒混凝土', addr:'苗栗縣後龍鎮龍坑里十班坑171-7號', lat:24.618, lng:120.787, group:'2star',
        detail:'資本額3,850萬｜1986年｜負責人林登倫', relations:{me:'錦鋒混凝土', members:[{name:'林登倫',role:'董事長',companies:['錦鋒混凝土','中來工業']},{name:'邱弘鎮',role:'董事',companies:['錦鋒混凝土']},{name:'陳國華',role:'董事',companies:['錦鋒混凝土']},{name:'黃清江',role:'董事',companies:['錦鋒混凝土']},{name:'江慶賜',role:'監察人',companies:['錦鋒混凝土']}]} },
      { name:'協鑫混凝土', addr:'苗栗縣大湖鄉富興村八寮灣25-15號', lat:24.421, lng:120.868, group:'2star',
        detail:'資本額4,000萬｜2007年｜負責人賴柊源', relations:{me:'協鑫混凝土', members:[{name:'賴柊源',role:'董事長',companies:['協鑫混凝土']},{name:'侯百能',role:'董事',companies:['協鑫混凝土']},{name:'蔡清榮',role:'監察人',companies:['協鑫混凝土']}]} },
      { name:'福宏實業', addr:'苗栗縣銅鑼鄉中平村七十份101號', lat:24.478, lng:120.787, group:'2star',
        detail:'資本額2,500萬｜1979年｜負責人張煥林', relations:{me:'福宏實業', members:[{name:'張煥林',role:'董事長',companies:['福宏實業','竹進企業']},{name:'賴瑞星',role:'董事',companies:['福宏實業']},{name:'張森鴻',role:'董事',companies:['福宏實業']},{name:'張國鴻',role:'董事',companies:['福宏實業']},{name:'張煥昇',role:'董事',companies:['福宏實業']},{name:'賴耀星',role:'監察人',companies:['福宏實業']}]} },
      { name:'頭份混凝土有限公司', addr:'苗栗縣苗栗市文聖里文山231之2號', lat:24.5615, lng:120.8192, group:'2star',
        detail:'資本額待查｜苗栗市預拌廠 | TRMC會員', relations:{me:'頭份混凝土有限公司', members:[{name:'張順雄',role:'董事',companies:['頭份混凝土有限公司']}]} },
    
      { name:'毅和實業（大厝廠）', addr:'苗栗縣竹南鎮真和路253巷26號', lat:24.686, lng:120.872, group:'3star' },
    ]
  },
  taichung: {
    label:'台中·彰化', center:[24.13,120.58], zoom:10,
    markers:[
      { name:'國產建材實業（台中廠）', addr:'臺中市南屯區寶山里工業區二十一路1號', lat:24.149, lng:120.581, group:'5star',
        detail:'國產建材2504｜台中廠｜負責人趙子敏', relations:null },
      { name:'亞東預拌混凝土（台中廠/遠東關係）', addr:'臺中市西屯區協和里工業區三五路38號', lat:24.151, lng:120.589, group:'5star',
        detail:'遠東集團亞泥100%轉投資｜資本額20億｜負責人李坤炎｜台中廠', relations:null },
      { name:'亞東預拌混凝土（大里廠）', addr:'412台中市大里區環河路一段470號', lat:24.0925, lng:120.6471, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜中區營運處｜大里廠｜GRMC認證', relations:null },
      { name:'亞東預拌混凝土（烏日廠）', addr:'414台中市烏日區溪南路三段418巷210號', lat:24.0483, lng:120.6523, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜中區營運處｜烏日廠｜GRMC認證', relations:null },
      { name:'亞東預拌混凝土（潭子廠）', addr:'台中市潭子區環中路一段3號', lat:24.2009, lng:120.7029, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜中區營運處｜潭子廠', relations:null },
      { name:'亞東預拌混凝土（霧峰廠）', addr:'台中市霧峰區中投西路2段540號', lat:24.0761, lng:120.6635, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜中區營運處｜霧峰廠', relations:null },
      { name:'台灣水泥（台中水泥製品廠）', addr:'臺中市大雅區中清路三段785號', lat:24.213212, lng:120.649157, group:'5star',
        detail:'台泥集團1101｜台中廠｜1978年設立｜綠色工廠認證｜ISO50001｜低碳混凝土', relations:null },
      { name:'環球混凝土（烏日廠/環泥子公司）', addr:'臺中市烏日區中山路一段665號', lat:24.104, lng:120.632, group:'4star',
        detail:'環球水泥(環泥)子公司｜GRMC認證｜供應中部科學園區', relations:null },
      { name:'興威股份有限公司', addr:'臺中市南屯區寶山里工業區二十一路56號', lat:24.149, lng:120.582, group:'4star',
        detail:'資本額1.91億｜1993年｜負責人顏子芳｜GRMC認證｜台中在地指標廠', relations:null },
      { name:'廣達混凝土股份有限公司', addr:'臺中市南屯區工業區二十路20號', lat:24.150, lng:120.580, group:'3star',
        detail:'資本額6,000萬｜1987年｜負責人羅國源｜台中工業區', relations:{me:'廣達混凝土', members:[{name:'羅國源',role:'董事長',companies:['廣達混凝土','中來工業']},{name:'羅正嘉',role:'董事',companies:['廣達混凝土']},{name:'謝崇文',role:'董事',companies:['廣達混凝土']},{name:'劉芳柳',role:'董事',companies:['廣達混凝土']},{name:'陳重達',role:'董事',companies:['廣達混凝土']},{name:'潘文昇',role:'監察人',companies:['廣達混凝土']}]} },
      { name:'中來工業股份有限公司', addr:'臺中市大里區環河路一段188號', lat:24.104, lng:120.689, group:'3star',
        detail:'資本額1.2億｜1987年｜負責人｜大里廠｜供應屯區', relations:{me:'中來工業', members:[{name:'林登倫',role:'董事長',companies:['中來工業','錦鋒混凝土']},{name:'王天惠',role:'董事',companies:['中來工業']},{name:'張木鳳',role:'董事',companies:['中來工業']},{name:'羅國源',role:'董事',companies:['中來工業','廣達混凝土']},{name:'童國龍',role:'董事',companies:['中來工業']},{name:'魏渾成',role:'監察人',companies:['中來工業']}]} },
      { name:'長生預拌混凝土（烏日廠）', addr:'臺中市烏日區榮泉里中山路三段1335巷57之1號', lat:24.088, lng:120.615, group:'3star',
        detail:'資本額1.33億｜1987年｜負責人鍾雲城｜GRMC認證', relations:{me:'長生預拌混凝土', members:[{name:'鍾雲城',role:'董事長',companies:['長生預拌混凝土','佳生砂石企業']},{name:'歐賢誠',role:'董事',companies:['長生預拌混凝土']},{name:'鍾書胤',role:'董事',companies:['長生預拌混凝土','佳生砂石企業']},{name:'歐秋月',role:'監察人',companies:['長生預拌混凝土','佳生砂石企業']}]} },
      { name:'福鹿預拌混凝土', addr:'彰化縣鹿港鎮東石里鹿工南二路22號', lat:24.065, lng:120.432, group:'3star',
        detail:'資本額7,800萬｜1991年｜負責人黃周秀鶴｜鹿港彰濱工業區', relations:{me:'福鹿預拌混凝土', members:[{name:'黃周秀鶴',role:'董事長',companies:['福鹿預拌混凝土']},{name:'施振生',role:'董事',companies:['福鹿預拌混凝土']},{name:'施淵源',role:'董事',companies:['福鹿預拌混凝土']},{name:'施怡安',role:'董事',companies:['福鹿預拌混凝土']},{name:'施宏璋',role:'監察人',companies:['福鹿預拌混凝土']}]} },
      { name:'久連預拌混凝土', addr:'彰化縣福興鄉福興村福三路四段401號1樓', lat:24.033, lng:120.433, group:'3star',
        detail:'資本額｜負責人梁國斌｜鹿港福興區', relations:{me:'久連預拌混凝土', members:[{name:'梁國斌',role:'董事',companies:['久連預拌混凝土']},{name:'梁妤甄',role:'監察人',companies:['久連預拌混凝土']}]} },
      { name:'裕山混凝土', addr:'彰化縣', lat:24.070, lng:120.480, group:'3star',
        detail:'彰化在地廠商（資料整理中）', relations:{me:'裕山混凝土', members:[{name:'黃漢主',role:'董事',companies:['裕山混凝土']}]} },
      { name:'全富混凝土工業', addr:'臺中市潭子區中山路一段309號', lat:24.211, lng:120.698, group:'2star',
        detail:'潭子廠｜中部區域供應', relations:{me:'全富混凝土工業', members:[{name:'劉弟科',role:'董事長',companies:['全富混凝土工業']},{name:'房松癸',role:'董事',companies:['全富混凝土工業']},{name:'賴榮樹',role:'董事',companies:['全富混凝土工業']},{name:'詹林淑芬',role:'監察人',companies:['全富混凝土工業']}]} },
      { name:'佳生砂石企業', addr:'臺中市大雅區昌平路三段620巷29號', lat:24.231, lng:120.635, group:'2star',
        detail:'砂石/預拌混凝土｜大雅廠', relations:{me:'佳生砂石企業', members:[{name:'鍾雲城',role:'董事長',companies:['佳生砂石企業','長生預拌混凝土']},{name:'林炎鏢',role:'董事',companies:['佳生砂石企業']},{name:'鍾書胤',role:'董事',companies:['佳生砂石企業','長生預拌混凝土']},{name:'歐秋月',role:'監察人',companies:['佳生砂石企業','長生預拌混凝土']}]} },
      { name:'伸太田工業', addr:'臺中市神岡區溪洲路202號', lat:24.273, lng:120.670, group:'2star',
        detail:'神岡廠｜中部區域供應', relations:{me:'伸太田工業', members:[{name:'王詳欽',role:'董事長',companies:['伸太田工業']},{name:'王利勝',role:'董事',companies:['伸太田工業']},{name:'劉妍楣',role:'董事',companies:['伸太田工業']},{name:'王允豐',role:'董事',companies:['伸太田工業']},{name:'王玟翔',role:'董事',companies:['伸太田工業']},{name:'王馮彩琴',role:'監察人',companies:['伸太田工業']}]} },
      { name:'豐崗實業', addr:'臺中市后里區堤防路2號', lat:24.306, lng:120.720, group:'2star',
        detail:'后里廠｜中部區域供應', relations:{me:'豐崗實業', members:[{name:'張繼中',role:'董事',companies:['豐崗實業']}]} },
      { name:'甲東洋土', addr:'臺中市西屯區大河里甘河路69號', lat:24.182, lng:120.651, group:'1star',
        detail:'西屯廠｜預拌混凝土', relations:{me:'甲東洋土', members:[{name:'李右祥',role:'董事長',companies:['甲東洋土']},{name:'李村培',role:'董事',companies:['甲東洋土']},{name:'曾素玲',role:'董事',companies:['甲東洋土']},{name:'李育如',role:'監察人',companies:['甲東洋土']}]} },
      { name:'民峰實業股份有限公司梧棲預拌混凝土廠', addr:'台中市梧棲區臨港路二段210號', lat:24.2549, lng:120.5316, group:'3star',
        detail:'民峰集團｜梧棲預拌廠 | TRMC會員', relations:{me:'民峰實業', members:[{name:'李林菊梅',role:'董事長',companies:['民峰實業']},{name:'林張淑芬',role:'董事',companies:['民峰實業']},{name:'林郁盛',role:'董事',companies:['民峰實業']},{name:'高鉦欽',role:'董事',companies:['民峰實業']},{name:'林汩杰',role:'董事',companies:['民峰實業']},{name:'林武雄',role:'監察人',companies:['民峰實業']}]} },
      { name:'野馬預拌混凝土有限公司', addr:'台中市龍井區臨港路一段880巷18號', lat:24.1927, lng:120.5458, group:'2star',
        detail:'資本額待查｜龍井區預拌廠 | TRMC會員', relations:{me:'野馬預拌混凝土', members:[{name:'林志銘',role:'董事',companies:['野馬預拌混凝土']}]} },
      { name:'埔塩預拌混凝土股份有限公司埔鹽廠', addr:'彰化縣埔鹽鄉埔港路63-4號', lat:24.0001, lng:120.4636, group:'2star',
        detail:'資本額待查｜埔鹽鄉預拌廠 | TRMC會員', relations:{me:'埔塩預拌混凝土', members:[{name:'陳美娟',role:'董事長',companies:['埔塩預拌混凝土']},{name:'梁宏任',role:'監察人',companies:['埔塩預拌混凝土']}]} },
      { name:'有駿預拌混凝土股份有限公司', addr:'彰化縣埤頭鄉彰水路四段468巷10號', lat:23.8914, lng:120.4622, group:'2star',
        detail:'資本額待查｜埤頭鄉預拌廠 | TRMC會員', relations:{me:'有駿預拌混凝土', members:[{name:'陳宥均',role:'董事長',companies:['有駿預拌混凝土']},{name:'陳羽涵',role:'董事',companies:['有駿預拌混凝土']},{name:'廖永隆',role:'董事',companies:['有駿預拌混凝土']},{name:'廖俊哲',role:'監察人',companies:['有駿預拌混凝土']}]} },
    
      { name:'台灣水泥（大肚分廠）', addr:'台中市大肚區沙田路二段303號', lat:24.153, lng:120.543, group:'5star' },
      { name:'興威股份有限公司（太平廠）', addr:'台中市太平區光興路327號', lat:24.129, lng:120.721, group:'4star' },
    ]
  },
  yunlin: {
    label:'雲林·嘉義·南投', center:[23.60,120.50], zoom:9,
    markers:[
      { name:'國產建材實業（嘉太廠）', addr:'嘉義縣太保市北港路二段91號', lat:23.465, lng:120.320, group:'5star',
        detail:'國產建材(2504)｜嘉太廠｜負責人陳以益', relations:null },
      { name:'國產建材實業（嘉義廠）', addr:'嘉義縣民雄鄉北斗村中山路50號', lat:23.555, lng:120.430, group:'5star',
        detail:'國產建材(2504)｜嘉義廠｜負責人陳以益', relations:null },
      { name:'國產建材實業（斗南廠）', addr:'雲林縣斗南鎮小東里公論路23號', lat:23.689, lng:120.465, group:'5star',
        detail:'國產建材(2504)｜斗南廠｜負責人吳國彰', relations:null },
      { name:'亞東預拌混凝土（雲林廠）', addr:'雲林縣虎尾鎮光明路73巷3-1號', lat:23.708, lng:120.437, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜雲林廠｜中區營運', relations:null },
      { name:'亞東預拌混凝土（布袋廠）', addr:'嘉義縣布袋鎮太平東路21巷1號', lat:23.376, lng:120.155, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜布袋廠｜嘉義區', relations:null },
      { name:'興威股份有限公司（草屯廠）', addr:'南投縣草屯鎮碧洲里草溪路73號', lat:23.985, lng:120.685, group:'4star',
        detail:'興農集團轉投資｜資本額1.91億｜GRMC認證#090｜草屯廠20車｜烏溪鳥嘴潭/八卦山隧道', relations:null },
      { name:'泉溢開發有限公司（朴子廠）', addr:'嘉義縣朴子市工業區三街57號', lat:23.462, lng:120.249, group:'3star',
        detail:'嘉義在地主要廠商｜供應嘉義海線', relations:{me:'泉溢開發', members:[{name:'李明華',role:'董事長',companies:['泉溢開發','佳毅營造']},{name:'陳献章',role:'董事',companies:['泉溢開發']},{name:'李珮瑜',role:'監察人',companies:['泉溢開發']}]} },
      { name:'承慶企業（山慶瀝青）', addr:'嘉義縣水上鄉中義路150號', lat:23.418, lng:120.393, group:'3star',
        detail:'水上廠｜預拌混凝土+瀝青混凝土', relations:{me:'承慶企業', members:[{name:'吳文瑞',role:'董事',companies:['承慶企業']}]} },
      { name:'煜昌工業', addr:'嘉義縣布袋鎮太平東路21巷1號', lat:23.375, lng:120.154, group:'3star',
        detail:'布袋廠｜預拌混凝土+水泥製品', relations:{me:'煜昌工業', members:[{name:'吳泰局',role:'董事長',companies:['煜昌工業']},{name:'吳陳碧珠',role:'監察人',companies:['煜昌工業']}]} },
      { name:'德欣先進', addr:'雲林縣斗六市萬年路700號', lat:23.722, lng:120.557, group:'3star',
        detail:'預拌+預鑄水泥製品｜斗六供應中南部', relations:{me:'德欣先進', members:[{name:'賴信義',role:'董事長',companies:['德欣先進','德欣投資']},{name:'賴建宏',role:'董事',companies:['德欣先進']},{name:'陳信宏',role:'董事',companies:['德欣先進']},{name:'賴建志',role:'監察人',companies:['德欣先進']}]} },
      { name:'益昌砂石企業', addr:'南投縣竹山鎮中和里前山路二段398號', lat:23.756, lng:120.689, group:'3star',
        detail:'GRMC認證合格｜竹山廠｜供應南投濁水線', relations:{me:'益昌砂石企業', members:[{name:'王鴻霖',role:'董事長',companies:['益昌砂石企業']},{name:'王秋滿',role:'董事',companies:['益昌砂石企業']},{name:'王秋菊',role:'監察人',companies:['益昌砂石企業']}]} },
      { name:'義展實業', addr:'南投縣埔里鎮大城里南環路899巷97號', lat:23.959, lng:120.968, group:'3star',
        detail:'埔里廠｜南投縣預拌公會會址｜供應埔里/魚池/國姓', relations:{me:'義展實業', members:[{name:'沈威潔',role:'董事長',companies:['義展實業']},{name:'林瑞麟',role:'董事',companies:['義展實業']},{name:'簡素珍',role:'監察人',companies:['義展實業']}]} },
      { name:'宏益達建材企業', addr:'嘉義縣梅山鄉工業一路38之6號', lat:23.590, lng:120.555, group:'3star',
        detail:'梅山工業區｜嘉義山線供應', relations:{me:'宏益達建材企業', members:[{name:'游順興',role:'董事',companies:['宏益達建材企業']}]} },
      { name:'宏進建材', addr:'嘉義縣太保市嘉太工業區中興路2號', lat:23.468, lng:120.318, group:'2star',
        detail:'嘉太工業區｜預拌混凝土製造', relations:{me:'宏進建材', members:[{name:'黃文賢',role:'董事',companies:['宏進建材']}]} },
      { name:'天源預拌混凝土', addr:'雲林縣斗六市石榴路369巷101號', lat:23.715, lng:120.578, group:'2star',
        detail:'斗六石榴班廠｜雲林在地供應', relations:null },
      { name:'任建企業', addr:'嘉義縣民雄鄉大崎村頂埤仔1之1號', lat:23.543, lng:120.450, group:'2star',
        detail:'民雄大崎村｜預拌混凝土', relations:{me:'任建企業', members:[{name:'林宗宏',role:'董事長',companies:['任建企業']},{name:'林李秋微',role:'監察人',companies:['任建企業']}]} },
      { name:'源順預拌混凝土', addr:'南投縣竹山鎮德興里坑巷32之1號', lat:23.728, lng:120.662, group:'1star',
        detail:'竹山在地小型廠', relations:null },
      { name:'聯成預拌混凝土', addr:'雲林縣台西鄉公館29號', lat:23.712, lng:120.198, group:'1star',
        detail:'台西廠｜雲林沿海供應', relations:{me:'聯成預拌混凝土', members:[{name:'林在地',role:'董事',companies:['聯成預拌混凝土']}]} },
      { name:'盛記預拌混凝土有限公司', addr:'雲林縣斗六市石寮路2之12號', lat:23.7051, lng:120.5373, group:'2star',
        detail:'資本額待查｜斗六市預拌廠 | TRMC會員', relations:{me:'盛記預拌混凝土', members:[{name:'郭麗玉',role:'董事',companies:['盛記預拌混凝土']}]} },
    
      { name:'台灣水泥（嘉義分廠）', addr:'嘉義縣民雄鄉北斗村新生街8號', lat:23.552, lng:120.432, group:'5star' },
      { name:'鳳勝實業（西螺廠）', addr:'雲林縣二崙鄉油車村山子門41號', lat:23.771, lng:120.415, group:'4star' },
      { name:'鳳勝實業（嘉泰廠）', addr:'嘉義縣太保市北港路二段105巷45號', lat:23.464, lng:120.332, group:'4star' },
      { name:'鳳勝實業（朴子廠）', addr:'嘉義縣朴子市朴子工業區一街16號', lat:23.464, lng:120.247, group:'4star' },
    ]
  },
  tainan: {
    label:'台南', center:[23.05,120.25], zoom:9,
    markers:[
      { name:'國產建材實業（台南廠）', addr:'台南市永康區洲尾街62號', lat:23.023, lng:120.250, group:'5star',
        detail:'國產建材(2504)｜台南廠｜負責人楊坪林', relations:null },
      { name:'亞東預拌混凝土（台南廠）', addr:'台南市南區新平路27號', lat:22.970, lng:120.180, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜台南廠｜南區營運', relations:null },
      { name:'亞東預拌混凝土（永康廠）', addr:'710台南市永康區三民里和平東路58號', lat:23.0551, lng:120.2635, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜嘉南區營運處｜永康廠', relations:null },
      { name:'亞東預拌混凝土（仁德廠）', addr:'台南市仁德區義林路70號', lat:22.9632, lng:120.2627, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜嘉南區營運處｜仁德廠（原太固實業廠址）', relations:null },
      { name:'亞東預拌混凝土（新營廠）', addr:'台南市新營區八德路3號', lat:23.305, lng:120.317, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜新營廠｜溪北營運', relations:null },
      { name:'台灣水泥（高雄水泥製品廠善化分廠）', addr:'台南市善化區興農路33號', lat:23.130, lng:120.300, group:'5star',
        detail:'台泥(1101)｜善化分廠｜GRMC認證#097｜180m³/h', relations:null },
      { name:'環球水泥（台南預拌混凝土場）', addr:'台南市南區中華西路一段59號', lat:22.977, lng:120.178, group:'4star',
        detail:'環球水泥(環泥)子公司｜台南廠', relations:null },
      { name:'名人預拌混凝土', addr:'台南市新市區中山路183號', lat:23.073, lng:120.297, group:'3star',
        detail:'1995年｜GRMC認證｜全品項綠建材｜遠雄/中鼎/寶佳合作', relations:{me:'名人預拌混凝土', members:[{name:'李冠德',role:'董事長',companies:['名人預拌混凝土','名人綠混凝土','名強資產投資']},{name:'方子明',role:'董事',companies:['名人預拌混凝土']},{name:'邱智湧',role:'董事',companies:['名人預拌混凝土']},{name:'邱紫絹',role:'監察人',companies:['名人預拌混凝土']}]} },
      { name:'太固實業', addr:'台南市仁德區義林路70號', lat:22.970, lng:120.253, group:'3star',
        detail:'仁德廠｜供應大台南地區', relations:{me:'太固實業', members:[{name:'蔡三銀',role:'董事長',companies:['太固實業']},{name:'葉紀霖',role:'監察人',companies:['太固實業']}]} },
      { name:'竑榮實業', addr:'台南市官田區二鎮里工業南路20號', lat:23.180, lng:120.322, group:'3star',
        detail:'官田工業區｜預拌混凝土+水泥製品', relations:{me:'竑榮實業', members:[{name:'楊芳銘',role:'董事長',companies:['竑榮實業','立竑預拌','漢鴻實業','森榮營造']},{name:'楊聰評',role:'董事',companies:['竑榮實業']},{name:'楊芳誌',role:'董事',companies:['竑榮實業']},{name:'楊淑妃',role:'監察人',companies:['竑榮實業']}]} },
      { name:'豐旗實業', addr:'台南市麻豆區麻豆口10之2號', lat:23.184, lng:120.254, group:'2star',
        detail:'麻豆廠｜供應台南溪北地區', relations:{me:'豐旗實業', members:[{name:'林文傑',role:'董事長',companies:['豐旗實業']},{name:'林陳秀琴',role:'董事',companies:['豐旗實業']},{name:'林永祥',role:'董事',companies:['豐旗實業']},{name:'林宜靜',role:'監察人',companies:['豐旗實業']}]} },
      { name:'丁丁有限公司預拌混凝土廠', addr:'台南市玉井區工業街266號', lat:23.1222, lng:120.4574, group:'2star',
        detail:'資本額待查｜玉井區預拌廠 | TRMC會員', relations:{me:'丁丁有限公司', members:[{name:'蘇志明',role:'董事',companies:['丁丁有限公司']}]} },
      { name:'安筑混凝土有限公司', addr:'台南市新營區嘉芳里八德路三號', lat:23.3087, lng:120.317, group:'2star',
        detail:'資本額待查｜新營區預拌廠 | TRMC會員', relations:{me:'安筑混凝土有限公司', members:[{name:'謝秀萍',role:'董事',companies:['安筑混凝土有限公司']}]} },
      { name:'玉楠混凝土企業股份有限公司楠西廠', addr:'台南市楠西區鹿田里鹿陶洋1號', lat:23.1738, lng:120.4876, group:'2star',
        detail:'資本額待查｜楠西區預拌廠 | TRMC會員', relations:{me:'玉楠混凝土企業', members:[{name:'林漢忠',role:'董事長',companies:['玉楠混凝土企業']},{name:'林淑惠',role:'監察人',companies:['玉楠混凝土企業']}]} },
    
      { name:'國產建材實業（仁德廠）', addr:'台南市仁德區義林路138號', lat:22.978, lng:120.251, group:'5star' },
      { name:'國產建材實業（新市廠）', addr:'台南市善化區小新里小新營461號', lat:23.132, lng:120.303, group:'5star' },
      { name:'台灣水泥（台南分廠）', addr:'台南市仁德區太乙七街36號', lat:22.978, lng:120.251, group:'5star' },
      { name:'台灣水泥（安平分廠）', addr:'台南市南區新樂路84-2號', lat:22.972, lng:120.193, group:'5star' },
      { name:'鳳勝實業（仁德廠）', addr:'台南市仁德區勝利路227號', lat:22.978, lng:120.251, group:'4star' },
      { name:'鳳勝實業（新營廠）', addr:'台南市新營區東山路158號', lat:23.31, lng:120.317, group:'4star' },
      { name:'環球水泥（永康預拌廠）', addr:'台南市永康區興工路20號', lat:23.027, lng:120.26, group:'4star' },
      { name:'環球水泥（麻豆預拌廠）', addr:'台南市麻豆區麻工一路377號', lat:23.186, lng:120.245, group:'4star' },
      { name:'竑榮實業（安定廠）', addr:'台南市安定區許中營24之11號', lat:23.104, lng:120.237, group:'3star',
        detail:'竑榮實業關係企業｜安定廠', relations:{me:'竑榮實業', members:[{name:'楊芳銘',role:'董事長',companies:['竑榮實業','立竑預拌','漢鴻實業','森榮營造']},{name:'楊聰評',role:'董事',companies:['竑榮實業']},{name:'楊芳誌',role:'董事',companies:['竑榮實業']},{name:'楊淑妃',role:'監察人',companies:['竑榮實業']}]} },
    ]
  },
  kaohsiung: {
    label:'高雄', center:[22.65,120.35], zoom:10,
    markers:[
      { name:'國產建材實業（仁武廠）', addr:'高雄市仁武區竹後里竹工三巷59號', lat:22.695, lng:120.349, group:'5star',
        detail:'國產建材(2504)｜仁武廠', relations:null },
      { name:'國產建材實業（鳳山廠）', addr:'高雄市大寮區江山里江山路81號', lat:22.604, lng:120.391, group:'5star',
        detail:'國產建材(2504)｜鳳山廠｜負責人潘建男', relations:null },
      { name:'亞東預拌混凝土（高雄廠）', addr:'高雄市大寮區永芳里萬丹路372號', lat:22.597, lng:120.396, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜高雄廠｜高屏區營運處', relations:null },
      { name:'亞東預拌混凝土（大順廠）', addr:'高雄市三民區民族一路556巷99號', lat:22.652, lng:120.308, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜大順廠', relations:null },
      { name:'亞東預拌混凝土（小港廠）', addr:'806高雄市前鎮區金福路10號', lat:22.5745, lng:120.3300, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜高屏區營運處｜小港廠', relations:null },
      { name:'亞東預拌混凝土（仁武廠）', addr:'81465高雄市仁武區鳳仁路322號', lat:22.7092, lng:120.3400, group:'5star',
        detail:'亞東預拌(遠東/亞泥)｜高屏區營運處｜仁武廠', relations:null },
      { name:'台灣水泥（高雄水泥製品廠）', addr:'高雄市仁武區工業一路16號', lat:22.695, lng:120.352, group:'5star',
        detail:'台泥(1101)｜仁武廠｜GRMC認證#011｜楠梓分廠另含2套拌合設備2500m³/日', relations:null },
      { name:'環球水泥（鳳山預拌混凝土場）', addr:'高雄市大寮區中庄里鳳屏一路146號', lat:22.613, lng:120.396, group:'4star',
        detail:'環球水泥(環泥)子公司｜鳳山廠', relations:null },
      { name:'鳳勝實業（仁武廠/總公司）', addr:'高雄市仁武區鳳仁路294號', lat:22.692, lng:120.350, group:'4star',
        detail:'鳳勝實業｜資本額6億｜台泥+官田鋼鐵股東｜全台11預拌廠+2砂石廠', relations:null },
      { name:'高屏預拌混凝土有限公司', addr:'高雄市美濃區自強街一段630號', lat:22.8979, lng:120.5415, group:'2star',
        detail:'資本額待查｜美濃區預拌廠 | TRMC會員', relations:{me:'高屏預拌混凝土', members:[{name:'林水木',role:'董事',companies:['高屏預拌混凝土']}]} },
    
      { name:'國產建材實業（小港廠）', addr:'高雄市小港區永春街11號', lat:22.565, lng:120.35, group:'5star' },
      { name:'國產建材實業（高雄廠）', addr:'高雄市左營區民族一路930-1號', lat:22.682, lng:120.295, group:'5star' },
      { name:'國產建材實業（岡山廠）', addr:'高雄市岡山區本洲路180號', lat:22.796, lng:120.295, group:'5star' },
      { name:'台灣水泥（小港分廠）', addr:'高雄市小港區中林路12號', lat:22.565, lng:120.35, group:'5star' },
      { name:'台灣水泥（仁武分廠）', addr:'高雄市仁武區工業一路16號', lat:22.702, lng:120.35, group:'5star' },
      { name:'台灣水泥（路竹分廠）', addr:'高雄市路竹區大仁路809號', lat:22.857, lng:120.26, group:'5star' },
      { name:'環球水泥（小港預拌廠）', addr:'高雄市小港區沿海三路20號', lat:22.565, lng:120.35, group:'4star' },
      { name:'環球水泥（大湖預拌廠）', addr:'高雄市路竹區環球路461之1號', lat:22.857, lng:120.26, group:'4star' },
      { name:'環球水泥（楠梓預拌廠）', addr:'高雄市燕巢區鳳龍巷58號', lat:22.793, lng:120.361, group:'4star' },
      { name:'竑榮實業（高雄廠）', addr:'高雄市大社區旗楠路80巷210號', lat:22.737, lng:120.354, group:'3star',
        detail:'竑榮實業關係企業｜高雄廠', relations:{me:'竑榮實業', members:[{name:'楊芳銘',role:'董事長',companies:['竑榮實業','立竑預拌','漢鴻實業','森榮營造']},{name:'楊聰評',role:'董事',companies:['竑榮實業']},{name:'楊芳誌',role:'董事',companies:['竑榮實業']},{name:'楊淑妃',role:'監察人',companies:['竑榮實業']}]} },
      { name:'竑榮實業（仁武廠）', addr:'高雄市仁武區工業二路11號', lat:22.702, lng:120.35, group:'3star',
        detail:'竑榮實業關係企業｜仁武廠', relations:{me:'竑榮實業', members:[{name:'楊芳銘',role:'董事長',companies:['竑榮實業','立竑預拌','漢鴻實業','森榮營造']},{name:'楊聰評',role:'董事',companies:['竑榮實業']},{name:'楊芳誌',role:'董事',companies:['竑榮實業']},{name:'楊淑妃',role:'監察人',companies:['竑榮實業']}]} },
    ]
  },
  pingtung: {
    label:'屏東', center:[22.55,120.55], zoom:10,
    markers:[
      { name:'鳳勝實業（屏東廠）', addr:'屏東縣屏東市橋南里工業五路8號', lat:22.656, lng:120.510, group:'4star',
        detail:'鳳勝實業｜屏東廠｜供應屏東市區', relations:null },
      { name:'鳳勝實業（高樹廠）', addr:'屏東縣高樹鄉新南村興店路2號', lat:22.785, lng:120.598, group:'3star',
        detail:'鳳勝實業｜高樹廠｜屏東北區供應', relations:null },
      { name:'鳳勝實業（佳冬廠）', addr:'屏東縣枋寮鄉東海村研發路85號', lat:22.365, lng:120.588, group:'2star',
        detail:'鳳勝實業｜佳冬廠(枋寮)｜屏東南區/墾丁半島供應', relations:null },
      { name:'鳳勝實業（恆春廠）', addr:'屏東縣車城鄉福興村中山路1號', lat:22.080, lng:120.713, group:'1star',
        detail:'鳳勝實業｜恆春廠｜墾丁/恆春半島供應', relations:null },
      { name:'城夆預拌混凝土有限公司九如廠', addr:'屏東縣九如鄉九如路二段1巷2號', lat:22.7398, lng:120.4901, group:'2star',
        detail:'資本額待查｜九如鄉預拌廠 | TRMC會員', relations:{me:'城夆預拌混凝土', members:[{name:'陳武雄',role:'董事',companies:['城夆預拌混凝土']}]} },
      { name:'超群混凝土工業股份有限公司內埔廠', addr:'屏東縣內埔鄉豐田村建富路7號', lat:22.612, lng:120.5669, group:'2star',
        detail:'資本額待查｜內埔鄉預拌廠 | TRMC會員', relations:{me:'超群混凝土工業', members:[{name:'楊金城',role:'董事長',companies:['超群混凝土工業']},{name:'楊侯碧霞',role:'監察人',companies:['超群混凝土工業']}]} },
    
      { name:'環球水泥（潮州預拌廠）', addr:'屏東縣潮州鎮光復路一段53號', lat:22.551, lng:120.543, group:'4star' },
    ]
  },
  taitung: {
    label:'台東', center:[22.85,121.08], zoom:9,
    markers:[
      { name:'佛育企業', addr:'台東市吉林路一段1266號', lat:22.7779, lng:121.1696, group:'2star',
        detail:'資本額1,000萬｜1994年｜負責人吳康源｜預拌混凝土製造', relations:{me:'佛育企業', members:[{name:'林明賢',role:'董事長',companies:['佛育企業','亞灣飯店','以寬建設']},{name:'林鑫池',role:'董事',companies:['佛育企業']},{name:'易宇柔',role:'董事',companies:['佛育企業']},{name:'林家宏',role:'監察人',companies:['佛育企業']}]} },
      { name:'本上企業', addr:'台東市中興路四段2巷135號', lat:22.7742, lng:121.0966, group:'2star',
        detail:'資本額500萬｜1994年｜負責人莊玉葉｜花東逾30年專業預拌廠｜砂石/水泥/混凝土', relations:{me:'本上企業', members:[{name:'吳宗翰',role:'董事',companies:['本上企業']}]} },
      { name:'延昌混凝土', addr:'台東市中興路四段133巷9弄90號', lat:22.7740, lng:121.0955, group:'2star',
        detail:'資本額2,000萬｜1993年｜負責人林昱廷｜預拌混凝土/水泥製品/土石採取', relations:{me:'延昌混凝土', members:[{name:'蘇寬鴻',role:'董事',companies:['延昌混凝土']}]} },
      { name:'陽宸企業', addr:'台東市中興路四段2巷165號', lat:22.7742, lng:121.0968, group:'2star',
        detail:'資本額2,400萬｜2006年｜負責人陳俊良｜預拌混凝土/水泥製品/土石採取', relations:{me:'陽宸企業', members:[{name:'侯秋霞',role:'董事',companies:['陽宸企業','甲宸交通']}]} },
      { name:'瑞晟砂石', addr:'台東市中華路四段998巷360號', lat:22.718, lng:121.098, group:'2star',
        detail:'資本額2,000萬｜2006年｜負責人張美玉｜砂石/預拌混凝土｜填土工程承攬', relations:{me:'瑞晟砂石', members:[{name:'許政雄',role:'董事',companies:['瑞晟砂石']}]} },
      { name:'志昇預拌混凝土', addr:'關山鎮順興路27之2號', lat:23.0566, lng:121.1709, group:'2star',
        detail:'資本額2,900萬｜1995年｜負責人黃榮鴻｜電腦全自動控制｜關山/池上/南橫供應',
        specs:'設備 電腦全自動拌和｜標準地磅｜服務台東關山池上', relations:{me:'志昇預拌混凝土', members:[{name:'黃榮鴻',role:'董事',companies:['志昇預拌混凝土']}]} },
      { name:'鹿原砂石場', addr:'鹿野鄉中華路三段60巷9號', lat:22.9396, lng:121.1427, group:'1star',
        detail:'資本額200萬｜1999年｜負責人戴昕恩｜砂石/預拌混凝土', relations:{me:'鹿原砂石場', members:[{name:'王建惠',role:'負責人',companies:['鹿原砂石場','鹿原有限公司','宏騰砂石','宏陽沙石']}]} },
      { name:'久明企業', addr:'大武鄉大竹村愛國蒲路74號', lat:22.4557, lng:120.9247, group:'1star',
        detail:'資本額1,000萬｜1997年｜負責人林建平｜預拌混凝土/土石採取｜南迴線供應', relations:{me:'久明企業', members:[{name:'張竣智',role:'董事',companies:['久明企業']}]} },
      { name:'綠寶實業', addr:'台東市蘭州街88號1樓', lat:22.7706, lng:121.1241, group:'1star',
        detail:'資本額500萬｜2024年新設｜負責人張家瑜｜預拌混凝土製造', relations:{me:'綠寶實業', members:[{name:'張家瑜',role:'董事',companies:['綠寶實業','是聿投資']}]} },
      { name:'尚聖營造', addr:'綠島鄉南寮路102之6號', lat:22.6593, lng:121.4756, group:'1star',
        detail:'丙等營造｜預拌混凝土製造｜綠島在地供應｜負責人張宏彬', relations:{me:'尚聖營造', members:[{name:'鄭蘇照蘭',role:'董事',companies:['尚聖營造']}]} }
    ]
  }
};